num_humans: 1 #number of human controlled robots
num_ais: 1 #number of ai controlled robots
width: 640 #width of camera view
height: 480 #height of camera view
timer: 10000 #play time in seconds
cell_size: 0.5 #Cell size for occupancy map
