num_humans: 0 #number of human controlled robots
num_ais: 1 #number of ai controlled robots
width: 360 #width of camera view
height: 240 #height of camera view
timer: 0 #play time in seconds, 0 if infinite play time
cell_size: 0.5 #Cell size for occupancy map
sensor_waiting_time: 0 #How much time to wait until sensor becomes available again after usage
ai_skip_frames: 0 #Skip frames to simulate human response time
fps: 0 #Target simulation frame rate. 0 means maximum possible
